### ISSUE TITLE
help for this panel 

### ISSUE THREAD

**Issue by Nickyg001** [cw2k/Adobe-GenP#11]
sometimes I get this screen and I don't understand what it is, if it's an error report or what... but above all I don't understand what I have to press on the buttons below.
Copy Data & Hdr/Row
Copy Data Only
etc....

![Immagine 2023-03-31 171606](https://user-images.githubusercontent.com/33684734/231781398-14c4e914-a437-4d6b-b7ff-9ed9c145a425.jpg)

**Comment by cw2k** [comment]
That is some left over from development. 
It shows an array with search and replace pattern.

Just click the X-button.
