### ISSUE TITLE
ARM version support request

### ISSUE THREAD

**Issue by dXrayb** [cw2k/Adobe-GenP#12]
Please support ARM version Photoshop

**Comment by cw2k** [comment]
Thanks for asking.

However I afraid but that's not possible.

The patch acts on processor opcode level.

The AMD Intel X64 CISC path and completly different path than the Motorola ARM RISC one.
Even if they might on high level share the same code base they will look when they got compiled very different.

Creating a patch for ARM will require to create another project.
