### ISSUE TITLE
session error?

### ISSUE THREAD

**Issue by suhexia** [cw2k/Adobe-GenP#14]
![image](https://github.com/cw2k/Adobe-GenP/assets/55019115/c6b39c13-33eb-43b2-8fc8-b7ce89b0f081)
I found some error : Get the elevated current session acccess token failed, returns -2147023584，I just try to open the program but raise that, i want to know how to solve this problem.

By the way, i try to run as  the administrator, but the result is same.

**Comment by suhexia** [comment]
I read the other issue and try to run NSudo.exe to open Adobe-GenP-3.0.exe i found it can run actively, but still can run with RunMe.exe, i dont know what problem is it

**Comment by Ikaros-521** [comment]
same

**Comment by suhexia** [comment]
> same

直接跑Resources里的Adobe-GenP.exe就行了，好像也没什么影响，都能打上不定

**Comment by Ikaros-521** [comment]
> > same
> 
> 直接跑Resources里的Adobe-GenP.exe就行了，好像也没什么影响，都能打上不定

有用！感谢
